version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/golang:1.11


  update_submodules: &update_submodules
    run:
      name: Update git submodules
      command: |
        git submodule update --init --remote --recursive

  install_dependencies: &install_dependencies
    run:
      name: Install dependencies
      command: |
        sudo apt-get update

        sudo apt-get install patch ghostscript nano

        pwd

        # Install wkhtmltopdf
        mkdir wkhtmltopdf_download
        cd wkhtmltopdf_download
        wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.trusty_amd64.deb
        sudo dpkg -i ./wkhtmltox_0.12.5-1.trusty_amd64.deb || sudo apt-get --fix-broken install
        cd ..
        rm -rf wkhtmltopdf_download/

        # verify versions
        grep --version
        sed --version
        wkhtmltopdf --version
        gs --version

  run_website_locally: &run_website_locally
    run:
      name: Patch terraform-website/Makefile and run website locally (in background)
      command: |
        echo "Patch terraform-website/Makefile to remove --tty"
        patch terraform-website/Makefile bin/Makefile.patch

        cd terraform-website

        make website &

        echo "Wait for site to start"
        sleep 10

        # Code from https://stackoverflow.com/a/42873372/550451
        curl --fail \
            --connect-timeout 5 \
            --max-time 10 \
            --retry 10 \
            --retry-delay 2 \
            --retry-max-time 40 \
            'http://localhost:4567/' > /dev/null

  generate_all: &generate_all
    run:
      name: Generate all
      command: |
        ./bin/generate.sh

jobs:
  build_all:
    machine: true
    working_directory: ~/project
    # <<: *container_config
    steps:
      - checkout     # - setup_remote_docker
      - *update_submodules
      - *install_dependencies
      - *run_website_locally
      - *generate_all

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_all


  build_all:
    jobs:
      - build_all:
          filters:
            branches:
              only: master
